---
- name: print server idle
  hosts: all
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      shell: df -h
      shell: uname -a
      register: out

    - debug: var=out.stdout_lines
