---
- name: print server idle
  hosts: all
  tasks:
    - name: Print disk usage and print deatils about the server
      shell: df -h
      shell: uname -a
      register: out

    - debug: var=out.stdout_lines
